[pytest]
pythonpath =
    .
    WIKI_MG/src
    storage/src
    wiki_agent/src
    ontology_core/src
    evolution/src
    relation/src
    ner/src
    dls/src
    preprocess
    pipeline/src
    aft/aft-main/src
cache_dir = .test-artifacts/root/.pytest_cache
addopts = --basetemp=.test-artifacts/root/tmp
